---
version: "2"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/jupyter_app
    env_file:
      - my.env
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: ["jupyter"]
